
export interface EditProfile {
    id: string,
    userid: string,
    profileimage?: string,
    images?: string[],
    username: string,
    email: string,
    gender?: string,
    location?: string,
    birthdate?: Date,
    language?: string[],
    aboutme?: string,
    collageName?: string,
    companyName?: string,
    instagranId?: string,
    height?: string,
    interest?: string,
    jobTitle?: string,
    liviningIn?: string,
    mobileno?: string,
    relationshipGoal?: string,
    relationshipType?: string,
    sexualOrientation?: string,
    askMeAbout: {
        goingOut?: string,
        myWeekends?: string,
        meandmyphone?: string,
    },
    basics: {
        zodiac?: string,
        eduction?: string,
        familyPlan?: string,
        communication?: string,
        covidVaccine?: string,
        personalityType?: string,
        loveStyle?: string,
    },
    lifeStyle: {
        pets?: string,
        dietaryPreference?: string,
        drinking?: string,
        sleepingHabits?: string,
        smoking?: string,
        socialMedia?: string,
        workout?: string,
    },
    premiumuser?: boolean,
    premiumtype?: string,
    premiumenddate?: Date,
    premiumstartdate?: Date,
}